  version: "3.7"

  services:
    django:
      build: 
        context : .
        dockerfile: Dockerfile
      command: python ./voynich/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"