# Generated by Django 3.1.3 on 2020-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classification',
            name='descr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classification',
            name='medievial_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classification',
            name='real_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classification',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classification',
            name='year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='misc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='page_image',
            field=models.ImageField(upload_to='site_media'),
        ),
    ]
