# Generated by Django 3.1.3 on 2021-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20201217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='page_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
