# Generated by Django 3.1.3 on 2021-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210103_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='page_image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
