# Generated by Django 3.1.3 on 2021-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20210103_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='svg',
            field=models.FileField(upload_to='imgs'),
        ),
    ]
