# Generated by Django 3.1.3 on 2021-01-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20210104_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='plant_Id',
            new_name='PlantID',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='person_Id',
            new_name='PublicationID',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='plant_Id',
            new_name='PlantID',
        ),
        migrations.CreateModel(
            name='PublicationToAutho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.person')),
                ('PublicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.publication')),
            ],
        ),
    ]
