# Generated by Django 3.1.3 on 2021-01-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20210107_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationToAutho',
            new_name='PublicationToAuthor',
        ),
    ]
