# Generated by Django 3.1.3 on 2021-01-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20210107_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='PublicationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.publication'),
        ),
    ]
