# Generated by Django 3.1.3 on 2021-01-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20210107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='medievial_image',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='real_image',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
