# Generated by Django 3.1.3 on 2021-08-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20210107_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='medievial_image',
            new_name='medieval_image',
        ),
        migrations.AlterField(
            model_name='classification',
            name='PlantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='plants.plant'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='PublicationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='plants.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('PlantID', 'PublicationID')},
        ),
    ]
