# Generated by Django 4.0.2 on 2022-03-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20210816_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='plants.Person'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='PublicationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.publication'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='page_image',
            field=models.ImageField(upload_to='voynich/imgs'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='svg',
            field=models.FileField(upload_to='voynich/imgs'),
        ),
    ]
